[
{ "objectID": "acute_2"},
{  "Coming from": ""},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "Is the chest pain acute or stable?"},
{ "question_class": ""},
{ "answer1": "Acute"},
{ "answer1_go_to:": "acute_3"},
{ "answer2": "stable"},
{ "answer2_go_to":"" "stableFig12_3"},
{ "answer3": ""},
{ "answer4": ""},
{ "answer3_go_to": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)": ""},
{ "Acute": ""},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": ""},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_3"},
{ "Coming from": "Acute> J2"},
{ "action_1": "Perform a physical exam, draw blood for the hs-cTn (or regular cTn), and perform ECG"},
{ "action1_class": "green"},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "Select determined cause of chest pain."},
{ "question_class": ""},
{ "answer1": "Obvious non-cardiac cause"},
{ "answer1_go_to:": "acute_4"},
{ "answer2": "Obvious non-ischemic cardiac cause"},
{ "answer2_go_to": "acute_5"},
{ "answer3": "STEMI"},
{ "answer3_go_to": "acute_6"},
{ "answer4": "Possible other ACS (not inc. STEMI)"},
{ "answer4_go_to": "acute_7"},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)": ""},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": ""},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_4"},
{ "Coming from": "Acute> J3"},
{ "action_1": "See Section 4.3. Evaluation of Acute Chest Pain With Suspected Noncardiac Causes in the 2021 Chest Pain Guideline"},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": ""},
{ "question_class": ""},
{ "answer1": ""},
{ "answer1_go_to:": ""},
{ "answer2": ""},
{ "answer2_go_to": ""},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)":
      'Section 4.3. Evaluation of Acute Chest Pain With Suspected Noncardiac Causes" : Insert JACC Anchor Tag for Section 4.3. Evaluation of Acute Chest Pain With Suspected Noncardiac Causes'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": "TRUE"},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": ""},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": "End"}
},
   "objectID": "acute_5"},
{ "Coming from": "Acute> L3"},
{ "action_1": "See Section 4.2. Evaluation of Acute Chest Pain With Nonischemic Cardiac Pathologies in the 2021 Chest Pain Guideline"},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": ""},
{ "question_class": ""},
{ "answer1": ""},
{ "answer1_go_to:": ""},
{ "answer2": ""},
{ "answer2_go_to": ""},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)":
      'Section 4.2. Evaluation of Acute Chest Pain With Nonischemic Cardiac Pathologies" :  Insert JACC Anchor tag for Section 4.2. Evaluation of Acute Chest Pain With Nonischemic Cardiac Pathologies'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": "TRUE"},
{ "STEMI": ""},
{ "Other ACS": ""},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": "End"}
},
{ "objectID": "acute_6"},
{ "Coming from": "Acute> N3"},
{ "action_1": "See 2013 STEMI Guideline"},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": ""},
{ "question_class": ""},
{ "answer1": ""},
{ "answer1_go_to:": ""},
{ "answer2": ""},
{ "answer2_go_to": ""},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)":
      'STEMI guidelines": https://www.jacc.org/doi/full/10.1016/j.jacc.2012.11.019?_ga=2.163803709.381967795.1626963202-1372334360.1532626008'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": "TRUE"},
{ "Other ACS": ""},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": "End"}
},
{ "objectID": "acute_7"},
{ "Coming from": "Acute> P3"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "Use a clinical decision pathway to risk stratify."},
{ "question_class": ""},
{ "answer1": "HEART pathway"},
{ "answer1_go_to:": "acute_8"},
{ "answer2": "EDACS"},
{ "answer2_go_to": "acute_9"},
{ "answer3": "ADAPT (mADAPT)"},
{ "answer3_go_to": "acute_10"},
{ "answer4": "NOTR"},
{ "answer4_go_to": "acute_11"},
{ "answer5": "ESC/ hs-cTn"},
{ "answer5_go_to": "acute_12"},
{ "answer6": "ESC/ GRACE"},
{ "answer6_go_to": "acute_13"},
{ "notes": ""},
{ "Links (URL)": ""},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_8"},
{ "Coming from": "Acute> J7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: HEART score <3\nNeg 0},
{ 3-h cTn\nNeg 0},
{ 2-h hs-cTn"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk:\nHEART score 4-6"},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk:\nHEART score 7-10"},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_9"},
{ "Coming from": "Acute> L7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: EDACS <16\nNeg 0}, 2 h hs-cTn\nNo ischemic ECG ∆"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk: N.A."},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk: N.A."},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_10"},
{ "Coming from": "Acute> N7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: TIMI score  0 (or <1 for mADAPT) Neg 0, 2-h cTn or hs-cTn\nNo ischemic ECG ∆"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk:\nTIMI score 2-4"},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk:\nTIMI score 5-7"},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_11"},
{ "Coming from": "Acute> P7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: Age <50 y\n<3 risk factors\nPrevious AMI or CAD\nNeg cTn or hs-cTn (0}, 2 h)"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk: NA"},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk: NA"},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_12"},
{ "Coming from": "Acute> R7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: Initial hs-cTn is “very low” and Sx onset >3 h ago\nor\nInitial hs-cTn “low” and 1-- or 2-h hs-cTn ∆  is “low”"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk:\nInitial hs-cTn is between “low” and “high”\nand/or\n1- or 2-h hs-cTn ∆ is between low and high thresholds"},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk:\nInitial hs-cTn is “high”\nor\n1- or 2-h hs-cTn ∆ is high"},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},
{  { "objectID": "acute_13"},
{ "Coming from": "Acute> T7"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "What is this patient's risk level?"},
{ "question_class": ""},
{ "answer1": "Low risk: Chest pain free}, GRACE <140\nSx <6 h - hs-cTn <ULN (0}, 3 h)\nSx >6 h - hs-cTn <ULN (arrival)"},
{ "answer1_go_to:": "acute_14"},
{ "answer2": "Intermediate risk:\nT0 hs-cTn = 12–52 ng/L or\n1-h ∆ = 3–5 ng/L"},
{ "answer2_go_to": "acute_15"},
{ "answer3": "High risk:\nT0 hs-cTn >52 ng/L or ∆ 1 h >5 ng/L"},
{ "answer3_go_to": "acute_16"},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes":
      "See Table 6. Sample Clinical Decision Pathways Used to Define Risk in in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI). See Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain"},
{ "Links (URL)":
      'table 6": Insert JACC Anchor tag to Table 6. Sample Clinical Decision Pathways Used to Define Risk in Section 4.1. Patients With Acute Chest Pain and Suspected ACS (Not Including STEMI).  "table 8": Insert JACC Anchor tag to Table 8. Definition Used for Low-Risk Patients With Chest Pain in Section 4.1.1. Low-Risk Patients With Acute Chest Pain'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_14"},
{ "Coming from": "Acute> J8/J9/J10/J11/J12/J13"},
{ "action_1":
      "No testing required; if patient has baseline cardiac risk factors}, consider pathways to facilitate outpatient follow-up for further evaluation and guideline-directed management of cardiac risk factors"},
{ "action1_class": "green"},
{ "action_2": "Discharge"},
{ "action2_class": "blue"},
{ "question": ""},
{ "question_class": ""},
{ "answer1": ""},
{ "answer1_go_to:": ""},
{ "answer2": ""},
{ "answer2_go_to": ""},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": "See Section 4.1.1. Low-Risk Patients With Acute Chest Pain for corresponding guideline recommendation."},
{ "Links (URL)":
      'Section 4.1.1" Insert JACC anchor tag to Section 4.1.1. Low-Risk Patients With Acute Chest Pain for corresponding guideline recommendation.'},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": "TRUE"},
{ "Intermediate Risk": ""},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": "TRUE"},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": "End"}
},
{ "objectID": "acute_15"},
{ "Coming from": "Acute> L8/L9/L10/L11/L12/L13"},
{ "action_1": ""},
{ "action1_class": ""},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": "Known CAD?"},
{ "question_class": ""},
{ "answer1": "No"},
{ "answer1_go_to:": "AcuteFig9>row 2"},
{ "answer2": "Yes"},
{ "answer2_go_to": "AcuteFig10>row 2"},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": ""},
{ "Links (URL)": ""},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": "TRUE"},
{ "High Risk": ""},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": ""},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": ""}
},,

  { "objectID": "acute_16"},
{ "Coming from": "Acute> N8/N9/N10/N11/N12/N13"},
{ "action_1": "Invasive coronary angiography"},
{ "action1_class": "green"},
{ "action_2": ""},
{ "action2_class": ""},
{ "question": ""},
{ "question_class": ""},
{ "answer1": ""},
{ "answer1_go_to:": ""},
{ "answer2": ""},
{ "answer2_go_to": ""},
{ "answer3": ""},
{ "answer3_go_to": ""},
{ "answer4": ""},
{ "answer4_go_to": ""},
{ "answer5": ""},
{ "answer5_go_to": ""},
{ "answer6": ""},
{ "answer6_go_to": ""},
{ "notes": "See Section X for corresponding guideline recommendation"},
{ "Links (URL)": ""},
{ "acute": "TRUE"},
{ "Obvious Non-cardiac Cause": ""},
{ "Obvious Non-ischemic Cardiac Cause": ""},
{ "STEMI": ""},
{ "Other ACS": "TRUE"},
{ "Low Risk": ""},
{ "Intermediate Risk": ""},
{ "High Risk": "TRUE"},
{ "No Known CAD": ""},
{ "Recent Negative Test": ""},
{ "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year": ""},
{ "Prior Moderate-Severely Abnormal ≤1 year": ""},
{ "Normal Stress Test (or mildly abnormal)": ""},
{ "Moderate-Severe Ischemia": ""},
{ "No CAD/Minimal Stenosis": ""},
{ "Obstructive CAD": ""},
{ "High-Risk CAD or Frequent Angina": ""},
{ "Intermediate Stenosis": ""},
{ "Intermediate/Inconclusive Stenosis": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia": ""},
{ "Known CAD": ""},
{ "Non-obstructive CAD": ""},
{ "Obstructive CAD__1": ""},
{ "High-Risk CAD or Frequent Angina__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__1": ""},
{ "Abnormal Functional Test": ""},
{ "Normal Functional Test": ""},
{ "stable": ""},
{ "No Known CAD__1": ""},
{ "Low Risk__1": ""},
{ "Intermediate/High Risk": ""},
{ "No CAD": ""},
{ "Non-obstructive CAD__1": ""},
{ "Obstructive CAD__2": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__2": ""},
{ "High-Risk CAD or Frequent Angina__2": ""},
{ "Tests Inconclusive": ""},
{ "Mild Ischemia": ""},
{ "Moderate-Severe Ischemia__1": ""},
{ "Persistent symptoms": ""},
{ "Known CAD__1": ""},
{ "Non-obstructive CAD__2": ""},
{ "Obstructive CAD__3": ""},
{ "Intensification of Preventive Strategies and Option to Defer Testing": ""},
{ "Persistent symptoms__1": ""},
{ "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3": ""},
{ "FFR-CT >0.8 or < Moderate-Severe Ischemia__3": ""},
{ "Intensify GDMT and Option to Defer Testing": ""},
{ "High-Risk CAD or Frequent Angina__3": ""},
{ "No ischemia": ""},
{ "Mild Ischemia__1": ""},
{ "Moderate-Severe Ischemia__2": ""},
{ "Invasive Coronary Angiography with FFR or IFR": ""},
{ "CCTA": ""},
{ "GDMT": ""},
{ "Discharge": ""},
{ "Optimize Preventive Therapies": ""},
{ "Continue Preventive Therapies": ""},
{ "Invasive Coronary Angiography": "TRUE"},
{ "Defer Invasive Coronary Angiography": ""},
{ "Preventive strategies and option to defer testing": ""},
{ "INOCA Pathway": ""},
{ "end": "End"}
]
