let acute_milestones = [
  "Obvious Non-cardiac Cause",
  "Obvious Non-ischemic Cardiac Cause",
  "STEMI",
  "Other ACS",
  "Low Risk",
  "Intermediate Risk",
  "High Risk",
  "No Known CAD",
  "Recent Negative Test",
  "Prior Inconclusive or Mildly Abnormal Stess Test ≤1 year",
  "Prior Moderate-Severely Abnormal ≤1 year",
  "Normal Stress Test (or mildly abnormal)",
  "Moderate-Severe Ischemia",
  "No CAD/Minimal Stenosis",
  "Obstructive CAD",
  "High-Risk CAD or Frequent Angina",
  "Intermediate Stenosis",
  "Intermediate/Inconclusive Stenosis",
  "FFR-CT ≤0.8 or Moderate-Severe Ischemia",
  "FFR-CT >0.8 or < Moderate-Severe Ischemia",
  "Known CAD",
  "Non-obstructive CAD",
  "Obstructive CAD__1",
  "High-Risk CAD or Frequent Angina__1",
  "FFR-CT ≤0.8 or Moderate-Severe Ischemia__1",
  "FFR-CT >0.8 or < Moderate-Severe Ischemia__1",
  "Abnormal Functional Test",
  "Normal Functional Test",
  "stable",
  "No Known CAD__1",
  "Low Risk__1",
  "Intermediate/High Risk",
  "No CAD",
  "Non-obstructive CAD__1",
  "Obstructive CAD__2",
  "FFR-CT ≤0.8 or Moderate-Severe Ischemia__2",
  "FFR-CT >0.8 or < Moderate-Severe Ischemia__2",
  "High-Risk CAD or Frequent Angina__2",
  "Tests Inconclusive",
  "Mild Ischemia",
  "Moderate-Severe Ischemia__1",
  "Persistent symptoms",
  "Known CAD__1",
  "Non-obstructive CAD__2",
  "Obstructive CAD__3",
  "Intensification of Preventive Strategies and Option to Defer Testing",
  "Persistent symptoms__1",
  "FFR-CT ≤0.8 or Moderate-Severe Ischemia__3",
  "FFR-CT >0.8 or < Moderate-Severe Ischemia__3",
  "Intensify GDMT and Option to Defer Testing",
  "High-Risk CAD or Frequent Angina__3",
  "No ischemia",
  "Mild Ischemia__1",
  "Moderate-Severe Ischemia__2",
  "Invasive Coronary Angiography with FFR or IFR",
  "CCTA",
  "GDMT",
  "Discharge",
  "Optimize Preventive Therapies",
  "Continue Preventive Therapies",
  "Invasive Coronary Angiography",
  "Defer Invasive Coronary Angiography",
  "Preventive strategies and option to defer testing",
  "INOCA Pathway",
  "end",
];
